### ISSUE TITLE
Latest update breaks inline editor's add links search

### ISSUE THREAD

**Issue by Ipstenu** [thingsym/custom-post-type-widgets#10]
With this plugin active, using the inline search for posts stops working. It no longer shows CPTs.

To reproduce:
- activate plugin and go to edit any post.
- select the text you want to make a link and click the link button (or ctrl-k in GUI editor).
- start typing. Only posts and pages will show up

If you click on the expanded view, you can (initially) see all the CPTs. It's only when you search that it fails :(

**Comment by Ipstenu** [comment]
I did a little rough testing.

If I comment out `inc/widget-custom-post-type-search.php` it works. Which is weird, since you're calling that under `widgets_init` and heavens knows that shouldn't load everywhere.

**Comment by bruno-barros** [comment]
It's really a bug.

The widget is changing the query parameter without any check. It break the WP search.

´´´
add_action( 'pre_get_posts', array( $this, 'query_search_filter_only_post_type' ) );
´´´

**Comment by thingsym** [comment]
Thank you. It was modified.

Fixed the behavior of the Dashboard or the administration panel.
