### ISSUE TITLE
 Categories do not appear

### ISSUE THREAD

**Issue by fredarend** [thingsym/custom-post-type-widgets#14]
Hello!
I own a CPT called Gallery and a CPT Taxonomy called Gallery Category.

In the "Categories (Custom Post Type)" widget, in the "Taxonomy" field the CPT Category Gallery does not appear.

As the image below:

![widget](https://user-images.githubusercontent.com/22778127/45827000-f1728f80-bccb-11e8-90c3-c9cd275aa084.png)

**Comment by thingsym** [comment]
Hi!

What is the setting of the **hierarchical** option of the register_taxonomy function?

> hierarchical
> (boolean) (optional) Is this taxonomy hierarchical (have descendants) like categories or not hierarchical like tags.
> Default: false

Reference:
https://codex.wordpress.org/Function_Reference/register_taxonomy

By hierarchical option,

If false, use "Tag Cloud (Custom Post Type)" as tags.
If true, use "Categories (Custom Post Type)" as categories.

**Comment by thingsym** [comment]
Hi!

What is the setting of the **hierarchical** option of the register_taxonomy function?

> hierarchical
> (boolean) (optional) Is this taxonomy hierarchical (have descendants) like categories or not hierarchical like tags.
> Default: false

Reference:
https://codex.wordpress.org/Function_Reference/register_taxonomy


By hierarchical option,

If false, use "Tag Cloud (Custom Post Type)" as tags.
If true, use "Categories (Custom Post Type)" as categories.

**Comment by thingsym** [comment]
Hi!

What is the setting of the **hierarchical** option of the register_taxonomy function?

> hierarchical
> (boolean) (optional) Is this taxonomy hierarchical (have descendants) like categories or not hierarchical like tags.
> Default: false

Reference:
https://codex.wordpress.org/Function_Reference/register_taxonomy


By hierarchical option,

If false, use "Tag Cloud (Custom Post Type)" as tags.
If true, use "Categories (Custom Post Type)" as categories.
