### ISSUE TITLE
Add link to the archive for Recent Post widget

### ISSUE THREAD

**Issue by andricicezar** [thingsym/custom-post-type-widgets#15]
I think it will be very useful if the Recent Post widget would include a link to the archive page (like: See More / See All).

What do you think?

**Comment by thingsym** [comment]
Hi, @andricicezar.
Thank you for your suggestion.

In version 1.2.0, the Custom Post Type Widgets has improved filter and action hooks.

You can add a link to the archive using the action hook `custom_post_type_widgets/recent_posts/widget/after`.

Sample code is as follows:

```
function cptw_hooks_setup() {
  add_action( 'custom_post_type_widgets/recent_posts/widget/after', 'cptw_recent_posts_after', 10, 3 );
}
add_action( 'after_setup_theme', 'cptw_setup_hooks' );

function cptw_recent_posts_after( $widget_id, $posttype, $instance ) {
  echo '<a href=' . get_post_type_archive_link( $posttype ) . '>';
  echo 'See All';
  echo '</a>';
}
```
