### ISSUE TITLE
thumbnails?

### ISSUE THREAD

**Issue by Generalnoob** [thingsym/custom-post-type-widgets#17]
Hi there love your script trying hoping you will add in (for recent posts) select all types and thumbnails please

**Comment by thingsym** [comment]
Hi, @Generalnoob.
Thank you for your suggestion.

In version 1.2.1, I've added a selection for all types to a Recent Posts.

**Comment by thingsym** [comment]
Hi, @Generalnoob.

You can use the action hook `custom_post_type_widgets/recent_posts/widget/prepend` to adding thumbnails.

Sample code is as follows:

```
function cptw_hooks_setup() {
  add_action( 'custom_post_type_widgets/recent_posts/widget/prepend', 'cptw_recent_posts_prepend', 10, 4 );
}
add_action( 'after_setup_theme', 'cptw_setup_hooks' );

function cptw_recent_posts_prepend( $widget_id, $posttype, $instance, $recent_post ) {
  if ( has_post_thumbnail( $recent_post ) ) {
    echo get_the_post_thumbnail( $recent_post );
  }
}
```

Insert the above code into functions.php in your theme.

Have fun!
